### ISSUE TITLE
Media player entity missing commands

### ISSUE THREAD

**Issue by albaintor** [unfoldedcircle/core-api#39] opened 2024-03-05 12:32 UTC
Actually the media player entity has most builtin commands : play/pause, arrow keys, home, back...
But some important commands are missing and are commonly used by media players :
- Context menu : popup menu for media streamers or bluray players (mapped to KEYCODE_TV_MEDIA_CONTEXT_MENU for android tv integration)
- Keypad numbers 0 to 9 : mapped to KEYCODE_0 > KEYCODE_9 for android TV integration for example => useful to create a dedicated numpad page
- Audio and subtitles language switching : this one is more tricky as there are no common commands, but they are usually mapped to keyboard keys
- Keyboard keys : A-Z (KEYCODE_A... for android TV integration). Some applications use keys as shortcuts (kodi) to enable audio/subtitles language switching, display or hide OSD or menu

The current workaround is to create individual home assistant scripts per command to make the link and add them to the remote.

Also a customizable "send command" in the UI where the user can type in the command could be a good idea too if you don't want to declare all the commands.

I know that the remote entity is also planned apart, but to avoid declaring 2 entities for the same device like in home assistant, I think you should consider adding some of those missing (common) commands, especially the context menu.

Thank you

**Comment by zehnm** [comment] 2024-03-05 12:39
Duplicate of #32

That's all there in the upcoming release!
Please check:
- https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_media_player.md
- https://github.com/unfoldedcircle/integration-python-library/blob/v0.1.6/ucapi/media_player.py

The UC media-player entity supports more features than the Home Assistant media-player entity. Furthermore, there are also "simple commands" to support any remaining device commands not covered by features (kind of a simple remote entity used in HA). This avoids exposing multiple entities.

**Closed by zehnm** 2024-03-05 12:39 UTC
Labels: enhancement

**Comment by albaintor** [comment] 2024-03-05 12:42
Awsome, thank you @zehnm , can't wait to get the next firmware !
